# Generated by Django 5.2.4 on 2025-07-15 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Aktenzeichen')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('case_type', models.CharField(choices=[('theft', 'Diebstahl'), ('fraud', 'Betrug'), ('assault', 'Körperverletzung'), ('drug', 'Drogen'), ('traffic', 'Verkehr'), ('domestic', 'Häusliche Gewalt'), ('other', 'Sonstiges')], max_length=20, verbose_name='Falltyp')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('closed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=2, verbose_name='Priorität (1-5)')),
                ('incident_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatzeitpunkt')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='Gemeldet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('involved_vehicles', models.ManyToManyField(blank=True, to='entities.vehicle', verbose_name='Beteiligte Fahrzeuge')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.address', verbose_name='Tatort')),
            ],
            options={
                'verbose_name': 'Fall',
                'verbose_name_plural': 'Fälle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_number', models.CharField(max_length=50, verbose_name='Beweis-Nr.')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('evidence_type', models.CharField(choices=[('document', 'Dokument'), ('photo', 'Foto'), ('video', 'Video'), ('audio', 'Audio'), ('physical', 'Physisches Objekt'), ('digital', 'Digitale Spur'), ('other', 'Sonstiges')], max_length=20, verbose_name='Beweistyp')),
                ('location_found', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fundort')),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='Datei')),
                ('chain_of_custody', models.TextField(blank=True, verbose_name='Verwahrungskette')),
                ('collected_date', models.DateTimeField(blank=True, null=True, verbose_name='Sichergestellt am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigations.case', verbose_name='Fall')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sichergestellt von')),
            ],
            options={
                'verbose_name': 'Beweismittel',
                'verbose_name_plural': 'Beweismittel',
                'ordering': ['-collected_date'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('investigation_type', models.CharField(choices=[('interview', 'Vernehmung'), ('search', 'Durchsuchung'), ('surveillance', 'Überwachung'), ('analysis', 'Analyse'), ('forensic', 'Forensische Untersuchung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Maßnahmentyp')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='Geplant für')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Durchgeführt am')),
                ('result', models.TextField(blank=True, verbose_name='Ergebnis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_investigations', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='investigations.case', verbose_name='Fall')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('target_persons', models.ManyToManyField(blank=True, to='entities.person', verbose_name='Zielpersonen')),
            ],
            options={
                'verbose_name': 'Ermittlungsmaßnahme',
                'verbose_name_plural': 'Ermittlungsmaßnahmen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvement_type', models.CharField(choices=[('suspect', 'Verdächtiger'), ('victim', 'Opfer'), ('witness', 'Zeuge'), ('informant', 'Informant'), ('other', 'Sonstiges')], max_length=20, verbose_name='Rolle')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('credibility', models.IntegerField(default=3, verbose_name='Glaubwürdigkeit (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.case', verbose_name='Fall')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person-Fall-Beteiligung',
                'verbose_name_plural': 'Person-Fall-Beteiligungen',
                'unique_together': {('person', 'case', 'involvement_type')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='involved_persons',
            field=models.ManyToManyField(through='investigations.PersonInvolvement', to='entities.person', verbose_name='Beteiligte Personen'),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datum/Zeit')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='investigations.case', verbose_name='Fall')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('related_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.address', verbose_name='Ort')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.person', verbose_name='Beteiligte Person')),
            ],
            options={
                'verbose_name': 'Zeitachsen-Eintrag',
                'verbose_name_plural': 'Zeitachsen-Einträge',
                'ordering': ['datetime'],
            },
        ),
    ]
