# Generated by Django 5.2.4 on 2025-07-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('urgent', 'Dringend')], default='medium', max_length=20, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('closed', 'Abgeschlossen'), ('suspended', 'Ausgesetzt')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
