# Generated by Django 5.2.4 on 2025-07-15 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Längengrad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
                'ordering': ['city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Geburtsort')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ausweisnummer')),
                ('known_aliases', models.TextField(blank=True, verbose_name='Bekannte Aliase')),
                ('risk_level', models.IntegerField(choices=[(0, 'Kein Risiko'), (1, 'Gering'), (2, 'Mittel'), (3, 'Hoch'), (4, 'Sehr hoch')], default=0, verbose_name='Risikostufe')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Kennzeichen')),
                ('vehicle_type', models.CharField(choices=[('car', 'PKW'), ('motorcycle', 'Motorrad'), ('truck', 'LKW'), ('bus', 'Bus'), ('other', 'Sonstiges')], default='car', max_length=20, verbose_name='Fahrzeugtyp')),
                ('make', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modell')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Farbe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.person', verbose_name='Besitzer')),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Wohnhaft seit')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Wohnhaft bis')),
                ('address_type', models.CharField(choices=[('primary', 'Hauptwohnsitz'), ('secondary', 'Nebenwohnsitz'), ('temporary', 'Temporär'), ('work', 'Arbeitsplatz'), ('other', 'Sonstiges')], default='primary', max_length=20, verbose_name='Adresstyp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.address', verbose_name='Adresse')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person-Adresse',
                'verbose_name_plural': 'Person-Adressen',
                'unique_together': {('person', 'address', 'address_type')},
            },
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('family', 'Familie'), ('friend', 'Freund'), ('colleague', 'Kollege'), ('neighbor', 'Nachbar'), ('associate', 'Bekannter'), ('suspect', 'Verdächtiger'), ('victim', 'Opfer'), ('witness', 'Zeuge'), ('other', 'Sonstiges')], max_length=20, verbose_name='Beziehungstyp')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('strength', models.IntegerField(default=1, verbose_name='Stärke (1-5)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Bekannt seit')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bekannt bis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='entities.person', verbose_name='Person 1')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='entities.person', verbose_name='Person 2')),
            ],
            options={
                'verbose_name': 'Beziehung',
                'verbose_name_plural': 'Beziehungen',
                'unique_together': {('person1', 'person2', 'relationship_type')},
            },
        ),
    ]
